@startmindmap compiler
caption Compiler Principle Overview
+ 编译原理
++_ 过程和各部分
++ 词法分析
+++ regex
+++ DFA
+++ NFA
+++ 状态图
+++ regex->NFA(Thompson/简化的)->DFA->DFA简化
++ 语法分析
+++ BNF
+++ EBNF(含语法图)
+++ First/Follow
+++ 文法
++++ 自顶向下
+++++ 递归下降伪代码
+++++ 左递归消除
+++++ 左公因式提取
+++++ LL(1)
++++ 自底向上
+++++ 活前缀
+++++ 短语
+++++ 句柄
+++++ LR(0)
+++++ SLR(1)
+++ 文法判定
+++ 自动机
+++ 分析表
-- 语义分析
--- SDD
----_ 综合属性
----_ 继承属性
--- SDT
---- 语义规则与语义动作
----_ S属性文法
----_ L属性文法
---- 属性计算
----- 依赖图
----- 树遍历
----- 一遍扫描
-- 代码生成(中间代码)
--- 格式
---- 后缀式
---- 图表示
---- 三地址码
----- 四元式
----- 三元式
----- 间接三元式
----- 赋值语句翻译
----- 布尔表达式翻译
------ 朴素翻译
------ 短路翻译
@endmindmap